### ISSUE TITLE
filedescriptor out of range in select()

### ISSUE THREAD

**Issue by jayendra13** [minrk/wurlitzer#22]
Here is the way to reproduce this.

    $ ulimit -n
    1048576

So the process can open max 1048576 files.
The following snippet is creating file descriptor objects which exceeds 1024 and puts the fid having greater than 1024 at that moment `select` function raises the error `ValueError: filedescriptor out of range in select()`

    import os, sys, select
    
    my_fd = sys.stdout.fileno()
    enough = False
    fids = []
    
    while not enough:
        f_ = os.dup(my_fd)
        fids.append(f_)
        if f_ > 1024:
            enough = True
    
    r, w, x = select.select(fids[-2:], [], [], None)

So my process has already opened 1K files and later I try to use Wurlitzer, it won't work.

https://mail.python.org/pipermail/python-list/2009-March/529177.html

**Comment by jayendra13** [comment]
This is the way I am trying to replace `select`  with `poll`, but things are not working. 

    def forwarder():
        """Forward bytes on a pipe to stream messages"""
        draining = False
        flush_interval = 0
        poller = select.poll()
        for pipe_ in pipes: poller.register(pipe_)
    
        while pipes:
            events = poller.poll(flush_interval)
            r = all([(r_[1] == (select.POLLIN | select.POLLPRI)) for r_ in events])
            if r:
                # found something to read, don't block select until
                # we run out of things to read
                flush_interval = 0
            else:
                # nothing to read
                if draining:
                    # if we are draining and there's nothing to read, stop
                    break
                else:
                    # nothing to read, get ready to wait.
                    # flush the streams in case there's something waiting
                    # to be written.
                    flush_queue.put('flush')
                    flush_interval = self.flush_interval
                    continue
    
            for fd, flags in events:
                if fd == self._control_r:
                    draining = True
                    os.close(self._control_r)
                    pipes.remove(self._control_r)
                    poller.unregister(self._control_r)
                    continue
                name = names[fd]
                data = os.read(fd, 1024)
                if not data:
                    # pipe closed, stop polling it
                    os.close(fd)
                    pipes.remove(fd)
                    poller.unregister(fd)
                else:
                    handler = getattr(self, '_handle_%s' % name)
                    handler(data)
            if not pipes:
                # pipes closed, we are done
                break

!!?

**Comment by jayendra13** [comment]
@minrk anything you can help here? thanks

**Comment by minrk** [comment]
I'm afraid I don't have any ideas or time at the moment.
