### ISSUE TITLE
Capturing redirected output

### ISSUE THREAD

**Issue by mrzv** [minrk/wurlitzer#37]
The following simple example behaves differently if I run it plain or with stdout redirected to a file (by the shell). Is this expected behavior? If yes, is there a way to capture output in the second case as well?

```python
from io import StringIO
from wurlitzer import pipes, STDOUT

def f():
    print("Hello from f")

out = StringIO()
with pipes(stdout=out, stderr=STDOUT):
    f()
print("Captured:", out.getvalue())
```

```
$ python test.py
Captured: Hello from f

```

```
$ python test.py > out
$ cat out
Hello from f
Captured:

**Comment by minrk** [comment]
Can you test with #38? I think that should solve it.

**Comment by mrzv** [comment]
Yup, works great. Thanks!
