### ISSUE TITLE
Running out of file descriptors

### ISSUE THREAD

**Issue by samousli** [minrk/wurlitzer#5]
I believe the file descriptors are left open, or there is a delay in their freeing.

I use pipes in a tight loop and it freezes at around 800~ iterations, I checked via
`ulimit -Sn` that the maximum allowed number of FDs are 1024. I believe that's the cause.

I may take a look at the issue myself once I find the time, but I'd appreciate your input.

**Comment by minrk** [comment]
Do you have a code example that does this? I think the exit of the context manager should be cleaning it up, but it might be doing so in a thread that takes a finite amount of time to do the actual cleanup.

**Comment by jayendra13** [comment]
Here is the way to reproduce this.

    $ ulimit -n
    1048576

So the process can open max 1048576 files.
The following snippet is creating file descriptor objects which exceeds 1024 and puts the fid having greater than 1024 at that moment `select` function raises the error `ValueError: filedescriptor out of range in select()`

    import os, sys, select
    
    my_fd = sys.stdout.fileno()
    enough = False
    fids = []
    
    while not enough:
        f_ = os.dup(my_fd)
        fids.append(f_)
        if f_ > 1024:
            enough = True
    
    r, w, x = select.select(fids[-2:], [], [], None)

https://mail.python.org/pipermail/python-list/2009-March/529177.html
