### ISSUE TITLE
Reason for failing to set pipe buffer size not shown with the corresponding warning

### ISSUE THREAD

**Issue by Dobiasd** [minrk/wurlitzer#57]
Hi, and first of all, thanks for `wurlitzer`. It's really helpful!. :+1:

While running something like the following

```python3
import cv2
from wurlitzer import pipes

with pipes() as (out, err):
    cv2.VideoCapture('foo')
print(out.read(), err.read())
```

during a Docker build step inside another Docker container (`dind`, GitLab CI, K8s), I noticed the following:

```
RuntimeWarning: Failed to set pipe buffer size
```

([line of code it originates from](https://github.com/minrk/wurlitzer/blob/7ce0c19442248049fc59db6a8e98d54d9a13b73f/wurlitzer.py#L209))

While things are working, I wonder why changing the capacity of a pipe does not work ([`fcntl` with `F_SETPIPE_SZ`](https://man7.org/linux/man-pages/man2/fcntl.2.html)). Maybe it's because my process is unprivileged and tries to set the pipe capacity above the limit in `/proc/sys/fs/pipe-max-size` (which would yield the error `EPERM`).

Would it be feasible to display the content/message of the `OSError` with the warning?

**Comment by minrk** [comment]
> Would it be feasible to display the content/message of the OSError with the warning?

Makes sense! Would you like to make a PR that updates the warning to include `str(error)`?

**Comment by Dobiasd** [comment]
Sure. :slightly_smiling_face:
https://github.com/minrk/wurlitzer/issues/57
