### ISSUE TITLE
ZQM error: Assertion failed: nbytes == sizeof dummy

### ISSUE THREAD

**Issue by cbourjau** [minrk/wurlitzer#6]
Hello,

thanks for this package! I have stumbled over a bug which seems to be related to zqm and was discussed in `cling` concerning the root jupyter kernel: https://github.com/root-project/cling/issues/123

Reproducing the issue
-----------------------------
Running the following in a jupyter-notebooke started with `jupyter-notebook` and `wurlitzer` installed from pip:
```
import ROOT
from wurlitzer import sys_pipes
f = ROOT.TFile.Open("test.root")
with sys_pipes():
    f.ls()
```

This causes the kernel to die and I get the following printed in the console:
```
Assertion failed: nbytes == sizeof dummy (src/signaler.cpp:196)
```

I know too little about jupyters inner workings, but I think this is related to the issue linked above. Might it be possible to port the fix developed there to wurlitzer?

Thanks again for publishing this package which seems to fill exactly my need, except that it crashes ;)

Cheers,
Christian

**Comment by minrk** [comment]
I'll have to think about it a bit. This could be a threading-related issue. What OS, Python, pyzmq, zeromq versions?

**Comment by cbourjau** [comment]
Thanks a lot for taking a look at this! The versions in play are:

- OS: Ubuntu 14.04
- Python: 2.7.6
- pyzmq: 16.0.2 (installed with pip)
- zeromq: AFAIKT, installed through pip; libzmq is not installed through apt
- jupyter: 1.0.0
- jupyter-client 5.0.1
- jupyter-console 5.1.0
- jupyter-core 4.3.0
