### ISSUE TITLE
`sys_pipes()` hangs on mac os

### ISSUE THREAD

**Issue by JakeSummers** [minrk/wurlitzer#84]
Running the following code causes `sys_pipes()` to hang on mac os.  

`__init__.py` file: 

```python
from wurlitzer import sys_pipes

print("Before")
with sys_pipes():
    print("After sys pipes")
print("Done")
```

Output is: 

<img width="841" alt="image" src="https://github.com/minrk/wurlitzer/assets/5657503/660be7d0-4fb1-4d4e-bb06-b55d76f854b9">

Computer info:

<img width="257" alt="image" src="https://github.com/minrk/wurlitzer/assets/5657503/2ba28b5c-97fc-48e5-9662-4f9e7c8e1e93">

Version info:

```
$ poetry show wurlitzer
 name         : wurlitzer
 version      : 3.0.3
 description  : Capture C-level output in context managers

$ python --version
Python 3.10.12
```

**I cannot reproduce when running in docker.**

**Comment by JakeSummers** [comment]
Maybe I am mis-using this tooling: 

https://github.com/minrk/wurlitzer/blob/d7f3ed1f11994a3d8309821cbf3ef4757831470d/wurlitzer.py#L537

**Comment by minrk** [comment]
You're right - `sys_pipes` is for forwarding things _to_ sys.stdout, when sys.stdout has already been replaced with something (e.g. in a Jupyter notebook).

I think perhaps what you want is `wurlitzer.pipes()`.

**Comment by minrk** [comment]
Hopefully #85 will give you a more meaningful error message that should point you in the right direction, rather than hanging uninformatively.

**Comment by JakeSummers** [comment]
Strangely, it looks like updating from `3.0.3` to `3.1.0` has resolved this issue.  

This code now works: 

```python
import sys
from contextlib import redirect_stderr

from wurlitzer import sys_pipes

# Tensorflow prints messages to stderr when it is imported.  These show up in
# GCP logging as errors.  To avoid this we are redirecting stderr to stdout.
#   See: https://github.com/tensorflow/tensorflow/issues/62770
#   And: https://stackoverflow.com/questions/77796003/how-to-redirect-tensorflow-import-errors-from-stderr-to-stdout

with redirect_stderr(sys.stdout):
    with sys_pipes():
        import tensorflow  # noqa: W0611
```

**Comment by minrk** [comment]
Yes, 3.1 optimizes forwarding to a file with a `fileno()` method in a way that shouldn't block. But that code ought to work, since it's doing this:

```python
# redirect_stderr:
sys.stderr = sys.stdout
# sys_pipes:
forward sys.__stdout__ to sys.stdout # this hung in 3.0, not in 3.1; this is why I have `stdout=None` in my example, to skip this step
forward sys.__stderr__ to sys.stderr # which is actually sys.stdout thanks to redirect_stderr
```
