### ISSUE TITLE
How to redirect c stderr to stdout

### ISSUE THREAD

**Issue by JakeSummers** [minrk/wurlitzer#87]
Currently the underlying c-library that I am using (tensorflow) is writing to stderr.  This is confusing my logging system. I would like to remap these errors from stderr to stdout.  

Currently I am doing this: 

```python
import sys
from contextlib import redirect_stderr

from wurlitzer import sys_pipes

# Tensorflow prints messages to stderr when it is imported.  These show up in
# GCP logging as errors.  To avoid this we are redirecting stderr to stdout.
#   See: https://github.com/tensorflow/tensorflow/issues/62770
#   And: https://stackoverflow.com/questions/77796003/how-to-redirect-tensorflow-import-errors-from-stderr-to-stdout
with redirect_stderr(sys.stdout):
    with sys_pipes():
        import tensorflow  # noqa: W0611
```

This seems to work however, I think that I am doing something that is explicitly advised against in the doc: 

https://github.com/minrk/wurlitzer/blob/0be57d9df7cea140528495764fd8c3c49780980e/wurlitzer.py#L532-L538

What is the proper way to redirect c-level stderr to stdout?

**Comment by minrk** [comment]
`redirect_stderr(sys.stdout)` sends Python `sys.stderr` to Python `sys.stdout`, it doesn't affect writes to the stderr FD, e.g. coming from C code. On the other hand, wurlitzer redirecting the low-level FD _does_ also capture sys.stderr (assuming sys.stderr hasn't been redirected already).

This should be sufficient:

```
import sys
from wurlitzer import pipes

# send stderr to stdout
with pipes(stdout=None, stderr=sys.stdout):
    sys.stdout.write("stdout\n")
    sys.__stdout__.write("__stdout__\n")
    sys.stderr.write("stderr\n")
    sys.__stderr__.write("__stderr__\n")
```

Or perhaps even simpler, if you want to do this permanently, you can merge the streams with one call:

```python
os.dup2(sys.stdout.fileno(), sys.stderr.fileno())
```

at the beginning of your application, and stderr will be permanently merged with stdout for the duration of the process.

**Comment by JakeSummers** [comment]
Thanks.  That works!  

Posted the solution here as well: https://stackoverflow.com/questions/77796003/how-to-redirect-tensorflow-import-errors-from-stderr-to-stdout
