### ISSUE TITLE
Live capture

### ISSUE THREAD

**Issue by ihincks** [minrk/wurlitzer#9]
I would be interesting in capturing stdout as it comes; I am trying to convert text printed to stdout into a jupyter progress bar. My first step is to just get it to print into the browser, but it all comes out after the code is finished, and 'out.count==1`. I have no idea what magic your module uses, so maybe this is not possible.

```
class CallbackWriter(object):
    def __init__(self, callback):
        self._callback = callback
        self.count = 0
        
    def write(self, s):
        self._callback(s)
        self.count +=1
        
    def writelines(self, iterable):
        for item in iterable:
            self.write(item)

def print_stdout(s):
    print s
out = CallbackWriter(print_stdout)
with pipes(stdout=out, stderr=STDOUT):
    # expensive code
```

**Comment by Lothiraldan** [comment]
You could override the `_handle_stdout` method and `_handle_stderr` in a subclass of Wunderlist

**Comment by ihincks** [comment]
No, sorry, I never followed through; I just continued switching windows into the terminal to see the output of pystan.

**Comment by minrk** [comment]
The above code works as-is, I believe:

```python
import wurlitzer
from IPython.display import display
from ipywidgets import IntProgress

class CallbackWriter:
    def __init__(self, callback):
        self._callback = callback
        self.count = 0
        
    def write(self, s):
        self._callback(s)
        self.count += 1
        
    def writelines(self, iterable):
        for item in iterable:
            self.write(item)

            
# expect 10 lines, so progress is complete when it's done
p = IntProgress(max=10)
display(p)

def on_stdout(s):
    print(f"Received {s!r}")  # debug to stdout. Don't do this if outside Jupyter because it will double-print to the captured pipe!
    # update progress based on completed lines
    p.value += s.count("\n")

out = CallbackWriter(on_stdout)

import ctypes
printf = ctypes.CDLL("libc.dylib").printf

with wurlitzer.pipes(stdout=out, stderr=wurlitzer.STDOUT):
    for i in range(10):
        printf(b"line\n")
        time.sleep(0.1)
```

which updates a progress bar based on the number of lines received. Of course, you could parse the lines of output if you know it contains information about progress, etc.

It seems like there isn't anything to do here since the given example works today. If it didn't work before, it may have been an issue in ipywidgets not always publishing state changes, but this is more reliable now. I'm going to close, but feel free to reopen if you have a specific case in mind that doesn't work.
